repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # adjust the revision as needed
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # adjust the revision as needed
    hooks:
      - id: flake8
